### ISSUE TITLE
[缺陷]无法正常发送加好友申请

### ISSUE THREAD

**Issue by VoltChange** [MakeDQFHappy/SoftWare_backend#20]
缺陷描述:
无法正常发送好友申请，用户ID为411393115791429的申请者和用户ID为430609259245637的接收者，介绍为“你好”,已确认两个用户均存在且并非已经为好友
涉及接口:
/api/friend/sendRequest
输入参数：
senderId:411393115791429
receiverId:430609259245637
introduction:你好
输出：
发送失败
![image](https://github.com/MakeDQFHappy/SoftWare_backend/assets/83451689/3c49aa15-b2d0-4e9e-acf6-b83ef070b3c6)
  请@hello596 修复

**Comment by Kenny00-exe** [comment]
@hello596

**Comment by hello596** [comment]
以修复

**Comment by hello596** [comment]
已修复

**Comment by hello596** [comment]
具体原因为判断是否已经是好友时多加了个！符号
解决方法为删除！符号

**Comment by hello596** [comment]
![图片](https://github.com/MakeDQFHappy/SoftWare_backend/assets/79883123/69d691a9-f8fc-4c62-ba22-45398696f8ad)
具体代码如上

**Comment by VoltChange** [comment]
回归测试确认通过
缺陷复盘:代码逻辑应为若已经是好友则返回false，原代码错误写为不是好友则返回false
