### ISSUE TITLE
[缺陷]发送好友申请时发送者和接收者可以为同一人问题

### ISSUE THREAD

**Issue by VoltChange** [MakeDQFHappy/SoftWare_backend#21]
缺陷描述:
在发送好友申请时，发送者和接收者错误地可以为同一人
涉及接口:
/api/friend/sendRequest
输入参数：
senderId:411393115791429
receiverId:411393115791429
introduction:你好
输出：
发送成功
预期结果：
发送失败
![image](https://github.com/MakeDQFHappy/SoftWare_backend/assets/83451689/3a33370e-a6b3-4b43-bcd3-59f981dd5f88)

**Comment by hello596** [comment]
错误原因：没有判断发送者和接收者是否是同一个人
解决方法：增加判断发送者和接收者是否是同一个人
代码如下：
![图片](https://github.com/MakeDQFHappy/SoftWare_backend/assets/79883123/b9d33246-bea7-4b40-bc36-696dc9e18837)

**Comment by VoltChange** [comment]
回归测试已通过
